# Generated by Django 6.0.1 on 2026-01-12 08:34

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.TextField()),
                ('event_date', models.DateField()),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('google_map_link', models.TextField(blank=True, null=True)),
                ('photographer', models.TextField(blank=True, null=True)),
                ('cinematographer', models.TextField(blank=True, null=True)),
                ('drone_operator', models.TextField(blank=True, null=True)),
                ('site_manager', models.TextField(blank=True, null=True)),
                ('assistant', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('sample_image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('role', models.TextField()),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('whatsapp_number', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.TextField()),
                ('category', models.TextField()),
                ('assigned_role', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='FileSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_member_name', models.TextField()),
                ('team_member_role', models.TextField()),
                ('file_name', models.TextField()),
                ('file_url', models.TextField()),
                ('file_type', models.TextField()),
                ('submission_type', models.TextField()),
                ('review_status', models.TextField(default='pending')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('role', models.TextField(choices=[('photographer', 'Photographer'), ('videographer', 'Videographer'), ('editor', 'Editor'), ('admin', 'Admin')], default='photographer')),
                ('team_size', models.TextField(blank=True, null=True)),
                ('plan_type', models.TextField(choices=[('basic', 'Basic'), ('advance', 'Advance'), ('premium', 'Premium'), ('unlimited', 'Unlimited')], default='basic')),
                ('years_in_business', models.TextField(blank=True, null=True)),
                ('weddings_per_year', models.TextField(blank=True, null=True)),
                ('services_offered', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True)),
                ('current_tools', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True)),
                ('referral_source', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeddingProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('couple_name', models.TextField()),
                ('event_date', models.DateField()),
                ('event_type', models.TextField(choices=[('Wedding', 'Wedding'), ('Engagement', 'Engagement'), ('Pre-wedding', 'Pre-wedding'), ('Reception', 'Reception')])),
                ('location', models.TextField()),
                ('service_type', models.TextField()),
                ('status', models.TextField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active')),
                ('progress_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('category', models.TextField(blank=True, null=True)),
                ('priority', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.TextField(blank=True, null=True)),
                ('estimated_hours', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('expected_deliverables', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.weddingproject')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.weddingproject'),
        ),
    ]
