# Generated by Django 5.2.10 on 2026-01-12 13:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembercontact',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammembercontact',
            name='invitation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='teammembercontact',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('sent', 'Invitation Sent'), ('joined', 'Joined'), ('failed', 'Invitation Failed'), ('left', 'Left Team')], default='pending'),
        ),
    ]
