# Generated by Django 5.2.10 on 2026-01-12 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teammembercontact_invitation_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.TextField(default='system')),
                ('language', models.TextField(default='en')),
                ('timezone', models.TextField(default='UTC')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('whatsapp_notifications', models.BooleanField(default=False)),
                ('project_reminders', models.BooleanField(default=True)),
                ('task_reminders', models.BooleanField(default=True)),
                ('event_reminders', models.BooleanField(default=True)),
                ('weekly_summary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
