# Generated by Django 5.2.10 on 2026-01-13 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembercontact',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammembercontact',
            name='name',
            field=models.TextField(),
        ),
    ]
