# Generated by Django 5.2.10 on 2026-01-13 11:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teammembercontact_owner_alter_teammembercontact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembercontact',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
