# Generated by Django 5.2.10 on 2026-01-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_teammembercontact_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.TextField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('submitted', 'Uploaded/Submitted')], default='upcoming'),
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.TextField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo'),
        ),
    ]
